export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const RETRIEVE_ROBOTS_PENDING = 'RETRIEVE_ROBOTS_PENDING';
export const RETRIEVE_ROBOTS_SUCCESS = 'RETRIEVE_ROBOTS_SUCCESS';
export const RETRIEVE_ROBOTS_FAILED = 'RETRIEVE_ROBOTS_FAILED';